version: '3.3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '10500:3000'
    command: "serve -s /app/build -p 3000"
    # command: npm start
    volumes:
      - './src:/app/src'
      - './public:/app/public'
